id = "ledger"
name = "Ledger"
version = "0.0.1"
schema_version = 1
authors = ["Clayton Carter <claytonrcarter@gmail.com>"]
description = "Ledger Plain Text Accounting support for Zed"
repository = "https://github.com/claytonrcarter/zed-language-ledger"

[grammars.ledger]
# repository = "https://github.com/cbarrete/tree-sitter-ledger"
# commit = "d313153eef68c557ba4538b20de2d0e92f3ef6f8"
repository = "https://github.com/claytonrcarter/tree-sitter-ledger"
commit = "eaaf3f92dc018ea84b382625059292e361a3ef88"

[language_servers.ledger-language-server]
name = "ledger-language-server"
language = "Ledger"
language_ids = { Ledger = "ledger" }
