id = "ledger"
name = "Ledger"
version = "0.0.1"
schema_version = 1
authors = ["Clayton Carter <claytonrcarter@gmail.com>"]
description = "Ledger Plain Text Accounting support for Zed"
repository = "https://github.com/claytonrcarter/zed-language-ledger"

[grammars.ledger]
# repository = "https://github.com/cbarrete/tree-sitter-ledger"
# commit = "8a841fb20ce683bfbb3469e6ba67f2851cfdf94a"
repository = "https://github.com/claytonrcarter/tree-sitter-ledger"
commit = "5ecde462948db959cec9ae379b22c732722e6ee8"

[language_servers.ledger-lsp]
name = "ledger-lsp"
language = "Ledger"
language_ids = { Ledger = "ledger" }
