id = "ledger"
name = "Ledger"
version = "0.0.1"
schema_version = 1
authors = ["Clayton Carter <claytonrcarter@gmail.com>"]
description = "Ledger Plain Text Accounting support for Zed"
repository = "https://github.com/claytonrcarter/zed-language-ledger"

[grammars.ledger]
# repository = "https://github.com/cbarrete/tree-sitter-ledger"
# commit = "d313153eef68c557ba4538b20de2d0e92f3ef6f8"
repository = "https://github.com/claytonrcarter/tree-sitter-ledger"
commit = "2657e59e0e57f451e790df05de6878de957b415b"

[language_servers.ledger-language-server]
name = "ledger-language-server"
language = "Ledger"
language_ids = { Ledger = "ledger" }
